baseurl = "/"
title = "llafuente"
fulltitle = """
  <span class="alt">undefined</span>man aka llafuente
  <a href="https://github.com/llafuente/" target="_blank">
    <i class="fa fa-github" aria-hidden="true"></i>
  </a>
"""
languageCode = "en-us"
theme = "hugo-theme-bootstrap4-blog"
copyright = """
Powered by <a href="https://gohugo.io/">Hugo</a>.
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
  <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" />
</a>
"""
pygmentsuseclasses = false
pygmentsstyle = "default"
googleAnalytics = "UA-87763666-1"
enableEmoji = true

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[permalinks]
  post = "/:year/:month/:filename/"
  code = "/:filename/"

[params]
  # Site author
  author = "Luis Lafuente"

  # Description/subtitle for homepage (can be Markdown)
  description = "Luis Lafuente dev blog."

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  # customise the contents of the navbar at the top of the page.  The default
  # behaviour is to list all static pages not in the posts directory. When the
  # parameter below is set to true you will have to manually add entries to the
  # navbar, either by adding the following menu variable to the front matter of
  # the relevant pages
  #   menu = "navbar"
  # or by specifying menu entries in a similar way to the sidebar menu above.
  #custom_navbar = true

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = """
Luis Lafuente dev blog in English... you have been warned!<br />
From Madrid, deep inside the dark matter talking about: Unity, web development, Arduino, games... and maybe more.
"""

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # Optional, used for attribution in Twitter cards
    # See: https://dev.twitter.com/cards/types/summary-large-image
    twitter = "username"

  [params.sharingicons]
    # Hide the sharing icons on posts? (Default: false)
    hide = false

    # Optionally, set any of these to false to hide them:
    #facebook = true
    #googleplus = true
    #linkedin = true
    #twitter = true

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]
